server:
  port: 9527

spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuu19527.com
    prefer-ip-address: true
info:
  app.name: shensm-springcloud
  company.name: blog.sheojsi.com


  #    www.shensm.com:9527/springcloud-provide-dept/dept/get/1
zuul:
  routes:
    mydept.serviceId: springcloud-provide-dept
    mydept.path: /mydept/**
  ignored-services: "*" #springcloud-provide-dept #不能在使用这个路径访问了，ignored:忽略，隐藏全部的，*代表所有
  #prefix: /shen  设置前缀